### PR TITLE
Fixes #73 Delete indexes if the exist before creating them.

### LINKED ISSUE #73: Indexes not dropped
We encountered an issue with the indexes not being dropped before they were created automatically in version 1.1.0.

I have a fix for it, but decided to log the issue to create a more transparent pull request.

### PR DESCRIPTION
**Pull request by geekdenz**

### CODE REVIEW

**Comment by dhensby** [comment]
Have you tested with latest 1.1.x-dev version because I've just merged in a fix around defined indexes?

I feel this is bad because the `drop if exists` is not part of the index definition and really we should be wrapping our index definition calls in the `$this->constraintExists()` checks...

I'm about to tag the latest 1.0, 1.1 and 1.2 releases as well as discontinue support for the 1.0 and 1.1 line after doing so... I'd appreciate you letting me know if the 1.1.x-dev solves this problem so I can do so without leaving you with a buggy 1.1 release

**Comment by geekdenz** [comment]
If you believe you have fixed it in this branch already and/or it's fixed in a later version, I'm happy to use that. I just wasn't sure it was, fixed it for us and then considered making a pull request in case it hadn't been fixed already. We will probably upgrade our version to the latest possible soon, but needed a fix fast today.

**Comment by tractorcow** [comment]
> I feel this is bad because the drop if exists is not part of the index definition and really we should be wrapping our index definition calls in the $this->constraintExists() checks...

I concur on this point. Can we shift the "if exists" closer to the point where we modify indexes?

**Comment by geekdenz** [comment]
Sure. Whatever works and is more in accordance with guidelines and principles of the project. I have merely done a hack that solved the problem for us quickly.

**Comment by dhensby** [comment]
Ok, I'm going close this as already fixed as I haven't heard to the contrary

**Pull request closed without merging**
